### ISSUE TITLE
cannot open ShooterGame.log error &&  tail: no files remaining

### ISSUE THREAD

**Issue by gdragon-git** [chandywerks/ark-ascended-docker#2]
ark-server  | tail: cannot open '/root/.steam/steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/Logs/ShooterGame.log' for reading: No such file or directory
ark-server  | tail: no files remaining

**Comment by morganplancot** [comment]
me too :/ help x)

**Comment by loginator** [comment]
I have created a PR for this issue:
[https://github.com/chandywerks/ark-ascended-docker/pull/3](url)

**Comment by ctmlr** [comment]
Happens on the first run. Fixed by adding --retry to the tail command. Thanks!
